name: Get overview of PR
on:
  pull_request:
    branches: ["master", "releases/**"]
  workflow_dispatch:
jobs:
  get-pr-overview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Call external API
        uses: actions/github-script@v7
        with:
          script: |
            const response = await fetch("https://twigs-upgrade-guide.vercel.app/api/get-diff", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "x-diff-secret-key": process.env.DIFF_API_SECRET
              },
              body: JSON.stringify({
                repo: `${context.repo.owner}/${context.repo.repo}`,
                pr: `${context.issue.number}`,
              }),
            });

            console.log(context.repo, context.repo.owner, context.repo.repo, context.issue.number);
            const data = await response.text();
            console.log(data);
        env:
          DIFF_API_SECRET: ${{ secrets.DIFF_API_SECRET }}
